name: Update Sublime API Docs

on:
  push:
    branches:    
      - master  
    paths:
    - 'sublime_version_list.json'

jobs:
  update-api-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install github3.py regex
    - name: Execute API Updates
      run: |
        python collect_api_version.py
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}